### ISSUE TITLE
White behind font??

### ISSUE THREAD

**Issue by Skrell** [Codextor/npp-material-theme#3]
![2018-03-06 11_05_41-c__temp_rfmodulation h - notepad](https://user-images.githubusercontent.com/590266/37043377-79ce6b68-212e-11e8-87af-8e8177cb3c83.png)

**Comment by Codextor** [comment]
This is a vestige of the default Notepad++ theme from which npp-material-theme is made.
In the default theme, in all the languages, the words have a white background.
This has been changed for the languages that our theme has been optimized for, say HTML, CSS, XML, SQL, etc. For other languages, changes need to be made.

**Comment by Codextor** [comment]
fixed by https://github.com/Codextor/npp-material-theme/commit/04f0dfacd849d1c6eacd89229df93c240acd213a
