### ISSUE TITLE
Theme is not appealing with C# code

### ISSUE THREAD

**Issue by GokulNC** [Codextor/npp-material-theme#5]
Theme is eye-straining for C# code, as seen below. 

![image](https://user-images.githubusercontent.com/10559293/45862959-a4f18780-bd91-11e8-95bb-2e0b48fedffd.png)

Notice how the font colors go along with the background color.
Any suggestions?

**Comment by Codextor** [comment]
**Hi @GokulNC, Thanks for trying out the theme.**
I've been updating the theme on a language by language basis. Since I don't really use C#, I never optimized the theme for it.
Not to worry, I'll do the needful and resolve the issue pretty soon.

**Comment by Codextor** [comment]
This is how C# files look now with the latest version of the theme applied. Hope this resolves the issue.
Please do try it out and let me know if you have any suggestions.

![issue 5](https://user-images.githubusercontent.com/9078554/47038957-5cff2e00-d1a0-11e8-8ac3-c3bbc8d0c3fd.PNG)

**Comment by Codextor** [comment]
fixed by 3086eb58d262e72cff2b11ef80a66164c502d2c7

**Comment by GokulNC** [comment]
Thanks for your fix :)
Looks cool now!
