### ISSUE TITLE
Theme is not appealing with OpenCL code

### ISSUE THREAD

**Issue by GokulNC** [Codextor/npp-material-theme#6]
![image](https://user-images.githubusercontent.com/10559293/47766356-3a1e5f00-dcf4-11e8-935d-81fb04038e6c.png)

**Comment by Codextor** [comment]
Hi @GokulNC Thanks for bringing up the issue.
The theme had not been optimised for Open CL code.
This should be resolved within a day.

**Comment by Codextor** [comment]
![capture](https://user-images.githubusercontent.com/9078554/47812788-48f62780-dd6f-11e8-921c-29200fe19e40.PNG)

This is how .cl files look now with the latest version of the theme applied. Hope this resolves the issue.
Please do try it out and let me know if you have any suggestions.

**Comment by GokulNC** [comment]
Looks cool now 💯 
Thank you so much :)
